In [80]:
import pandas as pd
confirmedData = pd.read_csv("time_series_19-covid-Confirmed.csv") 
deathData = pd.read_csv("time_series_19-covid-Deaths.csv")
recoveredData = pd.read_csv("time_series_19-covid-Recovered.csv")

In [81]:
tempDF = deathData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "deathFreq"]
DeathTimeSeries = tempDF
#DeathTimeSeries

In [82]:
tempDF = confirmedData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "confirmedFreq"]
ConfirmedTimeSeries = tempDF

In [83]:
tempDF = recoveredData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "recoveredFreq"]
RecoveredTimeSeries = tempDF

In [84]:
DeathTimeSeries.set_index('date').join(RecoveredTimeSeries.set_index('date'))
DeathTimeSeries.join(RecoveredTimeSeries.set_index('date'), on='date')

       date  deathFreq  recoveredFreq
0   1/22/20       17.0           28.0
1   1/23/20       18.0           30.0
2   1/24/20       26.0           36.0
3   1/25/20       42.0           39.0
4   1/26/20       56.0           52.0
5   1/27/20       82.0           61.0
6   1/28/20      131.0          107.0
7   1/29/20      133.0          126.0
8   1/30/20      171.0          143.0
9   1/31/20      213.0          222.0
10   2/1/20      259.0          284.0
11   2/2/20      362.0          472.0
12   2/3/20      426.0          623.0
13   2/4/20      492.0          852.0
14   2/5/20      564.0         1124.0
15   2/6/20      634.0         1487.0
16   2/7/20      719.0         2011.0
17   2/8/20      806.0         2616.0
18   2/9/20      906.0         3244.0
19  2/10/20     1013.0         3946.0
20  2/11/20     1113.0         4683.0
21  2/12/20     1118.0         5150.0
22  2/13/20     1371.0         6295.0
23  2/14/20     1523.0         8058.0
24  2/15/20     1666.0         9395.0
25  2/16/20     1770.0        10865.0
26  2/17/20     1868.0        12583.0
27  2/18/20     2007.0        14352.0
28  2/19/20     2122.0        16121.0
29  2/20/20     2247.0        18177.0
30  2/21/20     2251.0        18890.0
31  2/22/20     2458.0        22886.0
32  2/23/20     2469.0        23394.0
33  2/24/20     2629.0        25227.0
34  2/25/20     2708.0        27905.0
35  2/26/20     2770.0        30384.0
36  2/27/20     2814.0        33277.0
37  2/28/20     2872.0        36711.0
38  2/29/20     2941.0        39782.0
39   3/1/20     2996.0        42716.0
40   3/2/20     3085.0        45602.0
41   3/3/20     3160.0        48228.0
42   3/4/20     3254.0        51170.0
43   3/5/20     3348.0        53796.0
44   3/6/20     3460.0        55865.0
45   3/7/20     3558.0        58358.0
46   3/8/20     3802.0        60694.0
47   3/9/20     3988.0        62494.0
48  3/10/20     4290.0        64411.0
49  3/11/20     4647.0        67014.0

In [89]:
#Final
import pandas as pd
confirmedData = pd.read_csv("time_series_19-covid-Confirmed.csv") 
deathData = pd.read_csv("time_series_19-covid-Deaths.csv")
recoveredData = pd.read_csv("time_series_19-covid-Recovered.csv")

tempDF = deathData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "deathFreq"]
DeathTimeSeries = tempDF
#DeathTimeSeries
tempDF = confirmedData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "confirmedFreq"]
ConfirmedTimeSeries = tempDF

tempDF = recoveredData.sum(axis=0)
tempDF = tempDF.drop([tempDF.index[0] , tempDF.index[1]])

#tempDF = pd.DataFrame(data=tempDF)

tempDF = tempDF.reset_index()
tempDF.columns = ["date", "recoveredFreq"]
RecoveredTimeSeries = tempDF

TotalTimeSeries = ConfirmedTimeSeries.join(DeathTimeSeries.set_index('date'), on='date')
TotalTimeSeries = TotalTimeSeries.join(RecoveredTimeSeries.set_index('date'), on='date')
TotalTimeSeries.to_csv('TotalTimeSeries.csv', index = False, header=True)

In [88]:
TotalTimeSeries

       date  confirmedFreq  deathFreq  recoveredFreq
0   1/22/20          555.0       17.0           28.0
1   1/23/20          653.0       18.0           30.0
2   1/24/20          941.0       26.0           36.0
3   1/25/20         1434.0       42.0           39.0
4   1/26/20         2118.0       56.0           52.0
5   1/27/20         2927.0       82.0           61.0
6   1/28/20         5578.0      131.0          107.0
7   1/29/20         6166.0      133.0          126.0
8   1/30/20         8234.0      171.0          143.0
9   1/31/20         9927.0      213.0          222.0
10   2/1/20        12038.0      259.0          284.0
11   2/2/20        16787.0      362.0          472.0
12   2/3/20        19881.0      426.0          623.0
13   2/4/20        23892.0      492.0          852.0
14   2/5/20        27635.0      564.0         1124.0
15   2/6/20        30817.0      634.0         1487.0
16   2/7/20        34391.0      719.0         2011.0
17   2/8/20        37120.0      806.0         2616.0
18   2/9/20        40150.0      906.0         3244.0
19  2/10/20        42762.0     1013.0         3946.0
20  2/11/20        44802.0     1113.0         4683.0
21  2/12/20        45221.0     1118.0         5150.0
22  2/13/20        60368.0     1371.0         6295.0
23  2/14/20        66885.0     1523.0         8058.0
24  2/15/20        69030.0     1666.0         9395.0
25  2/16/20        71224.0     1770.0        10865.0
26  2/17/20        73258.0     1868.0        12583.0
27  2/18/20        75136.0     2007.0        14352.0
28  2/19/20        75639.0     2122.0        16121.0
29  2/20/20        76197.0     2247.0        18177.0
30  2/21/20        76823.0     2251.0        18890.0
31  2/22/20        78579.0     2458.0        22886.0
32  2/23/20        78965.0     2469.0        23394.0
33  2/24/20        79568.0     2629.0        25227.0
34  2/25/20        80413.0     2708.0        27905.0
35  2/26/20        81395.0     2770.0        30384.0
36  2/27/20        82754.0     2814.0        33277.0
37  2/28/20        84120.0     2872.0        36711.0
38  2/29/20        86011.0     2941.0        39782.0
39   3/1/20        88369.0     2996.0        42716.0
40   3/2/20        90306.0     3085.0        45602.0
41   3/3/20        92840.0     3160.0        48228.0
42   3/4/20        95120.0     3254.0        51170.0
43   3/5/20        97882.0     3348.0        53796.0
44   3/6/20       101784.0     3460.0        55865.0
45   3/7/20       105821.0     3558.0        58358.0
46   3/8/20       109795.0     3802.0        60694.0
47   3/9/20       113561.0     3988.0        62494.0
48  3/10/20       119298.0     4290.0        64411.0
49  3/11/20       126968.0     4647.0        67014.0